-- iolist

CREATE TABLE tbl_book(
    BOOK_SEQ	NUMBER	PRIMARY KEY,
    BOOK_ISBN	CHAR(13)	NOT NULL,	
    BOOK_TITLE	nVARCHAR2(100)	NOT	NULL,
    BOOK_AUTHOR	nVARCHAR2(100),		
    BOOK_PRICE	NUMBER,		
    BOOK_DESCRIPTION	nVARCHAR2(1000),		
    BOOK_IMAGE	nVARCHAR2(125),		
    BOOK_LINK	nVARCHAR2(255),		
    BOOK_RENT_YN	CHAR(1)
);

CREATE SEQUENCE SEQ_BOOK
START WITH 1
INCREMENT BY 1;


DROP TABLE tbl_usert;

CREATE TABLE tbl_user(
    USER_SEQ	NUMBER  PRIMARY KEY,
    USER_NAME	nVARCHAR2(100)	NOT	NULL,
    USER_BIRTH	CHAR(10),		
    USER_SEX	CHAR(1),
    USER_PHONE	nVARCHAR2(100)	NOT	NULL, -- 전화번호로 회원정보를 검색하는 KEY로 사용
    USER_EMAIL	nVARCHAR2(1000),		
    USER_IMAGE	nVARCHAR2(125),		
    USER_REG_DATE	CHAR(10),		
    USER_OUT_DATE	CHAR(10),		
    USER_OUT_YN	CHAR(1),		
    USER_RENT_COUNT	NUMBER,
    USER_RENT_TOTAL	NUMBER		
);

CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1;


CREATE TABLE tbl_rent(
    RENT_SEQ	NUMBER	PRIMARY KEY,
    RENT_DATE	CHAR(10)	NOT	NULL,
    RENT_RETURN_DATE	CHAR(10)	NOT	NULL,
    RENT_BOOK_SEQ	NUMBER	NOT	NULL,
    RENT_USER_SEQ	NUMBER	NOT	NULL,
    RENT_RETURN_YN	CHAR(1)		
);

CREATE SEQUENCE SEQ_RENT
START WITH 1
INCREMENT BY 1;


SELECT * FROM tbl_user;
